FROM ipython/scipyserver

RUN mkdir /basis_kurs
WORKDIR /basis_kurs
RUN mkdir ./cookbook ./data ./cookbook/images

COPY cookbook/*.ipynb ./cookbook/
COPY cookbook/images/*.png ./cookbook/images/
COPY data/* ./data/

WORKDIR /basis_kurs/cookbook/
